package com.catinsight.app.ui.theme

/** 對應 iOS CopySet:所有介面文案,依語言切換。 */
data class CopySet(
    val searchPlaceholder: String,
    val searchButton: String,
    val loadingText: String,
    val emptyPrompt: String,
    val fetchFailedPrefix: String,
    val noDataText: String,
    val notFoundText: String,
    val latestPrice: String,
    val preMarketPrice: String,
    val postMarketPrice: String,
    val useHistoricalFallback: String,
    val maLabel: String,
    val openLabel: String,
    val todayHighLabel: String,
    val todayLowLabel: String,
    val marketCapLabel: String,
    val fiftyTwoWeekHighLabel: String,
    val fiftyTwoWeekLowLabel: String,
    val epsLabel: String,
    val peRatioLabel: String,
    val dividendYieldLabel: String,
    val historyTitle: String,
    val newsTitle: String,
    val newsEmptyText: String,
    val moreButton: String,
    val lessButton: String,
    val listsTitle: String,
    val emptyListsText: String,
    val closeButton: String,
    val backToListButton: String,
    val languageTitle: String,
    val languageSubtitle: String,
    val themeTitle: String,
    val themeSubtitle: String,
    val darkThemeTitle: String,
    val darkThemeSubtitle: String,
    val lightThemeTitle: String,
    val lightThemeSubtitle: String,
    val preBadge: String,
    val postBadge: String,
    val regularBadge: String,
    val rsiLabel: String,
    val mfiLabel: String,
    val signalLabel: String,
    val strongLabel: String,
    val distributionLabel: String,
    val neutralLabel: String,
)

fun copySet(lang: AppLanguage): CopySet = when (lang) {
    AppLanguage.ZH -> CopySet(
        searchPlaceholder = "輸入股票代號或公司名，例如 NVDA、NVIDIA、台積電",
        searchButton = "查詢",
        loadingText = "資料載入中...",
        emptyPrompt = "請輸入股票代號後查詢",
        fetchFailedPrefix = "抓取失敗：",
        noDataText = "沒有收到資料",
        notFoundText = "找不到股票代號，請從下方候選結果選擇。",
        latestPrice = "最新價格",
        preMarketPrice = "盤前價格",
        postMarketPrice = "盤後價格",
        useHistoricalFallback = "使用歷史資料最新一筆",
        maLabel = "5MA",
        openLabel = "開盤價",
        todayHighLabel = "今日高點",
        todayLowLabel = "今日低點",
        marketCapLabel = "市值",
        fiftyTwoWeekHighLabel = "52週高點",
        fiftyTwoWeekLowLabel = "52週低點",
        epsLabel = "EPS",
        peRatioLabel = "本益比",
        dividendYieldLabel = "殖利率",
        historyTitle = "歷史明細",
        newsTitle = "新聞",
        newsEmptyText = "目前沒有相關新聞",
        moreButton = "展開",
        lessButton = "收起",
        listsTitle = "清單",
        emptyListsText = "還沒有加入任何股票",
        closeButton = "關閉",
        backToListButton = "回到股票list",
        languageTitle = "語言切換",
        languageSubtitle = "選擇你想要的顯示語言",
        themeTitle = "主題切換",
        themeSubtitle = "選擇你想要的介面風格",
        darkThemeTitle = "深色模式",
        darkThemeSubtitle = "深色背景與淺色文字",
        lightThemeTitle = "淺色模式",
        lightThemeSubtitle = "淺色背景與深色文字",
        preBadge = "盤前",
        postBadge = "盤後",
        regularBadge = "正常盤",
        rsiLabel = "RSI",
        mfiLabel = "MFI",
        signalLabel = "判斷",
        strongLabel = "強勢",
        distributionLabel = "主力出貨",
        neutralLabel = "中性",
    )
    AppLanguage.EN -> CopySet(
        searchPlaceholder = "Enter symbol or company name, e.g. NVDA, NVIDIA, TSMC",
        searchButton = "Search",
        loadingText = "Loading...",
        emptyPrompt = "Enter a stock symbol to begin",
        fetchFailedPrefix = "Fetch failed: ",
        noDataText = "No data received",
        notFoundText = "Symbol not found. Please choose from suggestions below.",
        latestPrice = "Latest Price",
        preMarketPrice = "Pre-Market Price",
        postMarketPrice = "After-Hours Price",
        useHistoricalFallback = "Using latest historical datapoint",
        maLabel = "5MA",
        openLabel = "Open",
        todayHighLabel = "Today's High",
        todayLowLabel = "Today's Low",
        marketCapLabel = "Market Cap",
        fiftyTwoWeekHighLabel = "52W High",
        fiftyTwoWeekLowLabel = "52W Low",
        epsLabel = "EPS",
        peRatioLabel = "P/E Ratio",
        dividendYieldLabel = "Dividend Yield",
        historyTitle = "Historical Details",
        newsTitle = "News",
        newsEmptyText = "No related news at the moment",
        moreButton = "More",
        lessButton = "Less",
        listsTitle = "Lists",
        emptyListsText = "No stocks in your list yet",
        closeButton = "Close",
        backToListButton = "Back to stock list",
        languageTitle = "Language",
        languageSubtitle = "Choose display language",
        themeTitle = "Theme",
        themeSubtitle = "Choose your interface style",
        darkThemeTitle = "Dark Mode",
        darkThemeSubtitle = "Dark background with light text",
        lightThemeTitle = "Light Mode",
        lightThemeSubtitle = "Light background with dark text",
        preBadge = "PRE",
        postBadge = "POST",
        regularBadge = "REGULAR",
        rsiLabel = "RSI",
        mfiLabel = "MFI",
        signalLabel = "Signal",
        strongLabel = "Strong",
        distributionLabel = "Distribution",
        neutralLabel = "Neutral",
    )
}
